language: python
python:
 - "3.5"

 # command to install dependencies
 install: "pip install -r requirements.txt"

 before_script:
  - python manage.py makemigrations

  script:
   - python manage.py migrate