# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagebox', '0009_productimage2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage2',
        ),
    ]
