# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagebox', '0011_제품이미지2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='제품이미지2',
        ),
    ]
